### PR TITLE
Feat:Added Product page

### PR DESCRIPTION
**Pull request by neetukumari4858**
Feat:Added Prod
Screenshot from 2022-02-20 22-47-40
uct

### CODE REVIEW

**Review by Avin008 — COMMENTED** [review]
Looks great. good to merge

**Comment by neetukumari4858** [comment]
Hey ,Avinash Mahananda can you approve the commit?

**Comment by neetukumari4858** [comment]
Hey,
Avinash Mahananda

thanks for review and can you Aprove  the comment.

**Review by Avin008 — APPROVED** [review]
Looks great. good to merge

**Review by sks-21 — APPROVED** [review]
The code looks nice. Good to merge.

**Pull request merged**
